@echo off
REM Removes generated build artefacts. Everything deleted here is regenerated by
REM Scripts\Build.bat.
REM
REM Every path is anchored to this script's location, and each is named explicitly
REM rather than matched recursively -- the previous approach ("del /S /Q *.sln"
REM from whatever the working directory happened to be) could reach well outside
REM the project.

setlocal

set ROOT=%~dp0..

echo Cleaning generated build artefacts...

if exist "%ROOT%\Binaries" (
    echo   Binaries\
    rmdir /S /Q "%ROOT%\Binaries"
)

for %%P in (
    "%ROOT%\The Forge.sln"
    "%ROOT%\TheForge\Engine\Engine.vcxproj"
    "%ROOT%\TheForge\Netcode\Netcode.vcxproj"
    "%ROOT%\Launcher\Launcher.vcxproj"
    "%ROOT%\Games\Project-Steel\Project-Steel.vcxproj"
) do (
    if exist %%P (
        echo   %%~nxP
        del /Q %%P
        if exist %%P.user del /Q %%P.user
        if exist %%P.filters del /Q %%P.filters
    )
)

echo Done. Run Scripts\Build.bat to regenerate and rebuild.
