name: Build Game Engine on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Enviroment
        run: |
          set PREMAKE_URL=https://github.com/premake/premake-core/releases/download/v5.0.0-beta5/premake-5.0.0-beta5-windows.zip
          set PREMAKE_DIR=%CD%\..\Premake\Windows

      - name: Install Premake
        run: |
          PowerShell -ExecutionPolicy Bypass -File .\Scripts\Utils\Setup-Premake.ps1 "%PREMAKE_URL%" "%PREMAKE_DIR%"

      - name: Build Launcher
        run: |
          # TODO: Finish Launcher

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./path/to/build/artifacts  # Specify the path to your build output
